export type Env={DETECTOR_API_KEY?:string;DETECTOR_API_URL?:string;DETECTOR_MODEL?:string;DETECTOR_MODEL_VERSION?:string;SAM2_API_KEY?:string;SAM2_API_URL?:string;SAM2_MODEL?:string;SAM2_MODEL_VERSION?:string;DEPTH_API_KEY?:string;DEPTH_API_URL?:string;DEPTH_MODEL?:string;DEPTH_MODEL_VERSION?:string;GEOMETRY_API_URL?:string;GEOMETRY_API_KEY?:string};
export type Point={x:number;y:number};export type Polygon=Point[];export type Det={label:string;confidence:number;box:number[];polygon:Polygon};export type Mask={id:string;label:string;confidence:number;polygon:Polygon;svgPath:string;alphaMaskUrl?:string};
const PRED="https://api.replicate.com/v1/predictions",MODELS="https://api.replicate.com/v1/models";
export const DETECTOR_MODEL="idea-research/grounding-dino",SAM_MODEL="meta/sam-2",DETECTOR_PROMPT="door . window . glass door . glass panel . light fixture . vent . column . sign . plant . protruding fixture";
export const path=(p:Polygon)=>p.length?`${p.map((q,i)=>`${i?"L":"M"}${q.x.toFixed(4)} ${q.y.toFixed(4)}`).join(" ")} Z`:"";
export const rect=(x:number,y:number,w:number,h:number):Polygon=>[{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}];
function modelUrl(model?:string){const[o,n]=(model??"").split("/");return o&&n?`${MODELS}/${o}/${n}/predictions`:PRED}
async function create(key:string,input:Record<string,unknown>,o:{api?:string;model?:string;version?:string}){const v=!!(o.version&&o.version!=="pending"),r=await fetch(v?(o.api||PRED):modelUrl(o.model),{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify(v?{version:o.version,input}:{input})});if(!r.ok)throw new Error(`Replicate create failed: ${r.status} ${await r.text()}`);return r.json()}
async function poll(pred:any,key:string){let cur=pred;for(let i=0;i<24;i++){if(cur.status==="succeeded")return cur;if(cur.status==="failed"||cur.status==="canceled")throw new Error(`Replicate ${cur.status}: ${cur.error??"no error"}`);if(!cur.urls?.get)throw new Error("Replicate prediction did not include a polling URL.");await new Promise(r=>setTimeout(r,i<5?900:1600));const res=await fetch(cur.urls.get,{headers:{Authorization:`Bearer ${key}`}});if(!res.ok)throw new Error(`Replicate poll failed: ${res.status} ${await res.text()}`);cur=await res.json()}throw new Error("Replicate prediction timed out.")}
export async function run(c:{key?:string;api?:string;model?:string;version?:string;input:Record<string,unknown>;label:string}){if(!c.key)throw new Error(`${c.label} API key missing.`);if((!c.model||c.model==="pending")&&(!c.version||c.version==="pending"))throw new Error(`${c.label} model missing.`);return poll(await create(c.key,c.input,{api:c.api,model:c.model,version:c.version}),c.key)}
function boxPoly(b:any):Polygon|null{if(!Array.isArray(b)||b.length<4)return null;let[x1,y1,x2,y2]=b.map(Number);if(![x1,y1,x2,y2].every(Number.isFinite))return null;if(x2<x1)[x1,x2]=[x2,x1];if(y2<y1)[y1,y2]=[y2,y1];const m=Math.max(x1,y1,x2,y2);if(m<=1.5)return rect(x1,y1,x2-x1,y2-y1);if(m<=100)return rect(x1/100,y1/100,(x2-x1)/100,(y2-y1)/100);return null}
export function dets(raw:any):Det[]{const out=raw?.output??raw,src=out?.detections??out?.objects??out?.boxes??out?.results??out;if(!Array.isArray(src))return[];return src.map((it:any,i:number)=>{const b=it?.box??it?.bbox??it?.bounding_box??it,p=it?.polygon??it?.points??boxPoly(b);return Array.isArray(p)&&p.length>=3?{label:String(it?.label??it?.class??it?.name??`detected ${i+1}`),confidence:Number(it?.confidence??it?.score??.65),box:Array.isArray(b)?b.map(Number):[],polygon:p}:null}).filter(Boolean) as Det[]}
export function masks(raw:any,ds:Det[]):Mask[]{const out=raw?.output??raw,ms=out?.masks??out?.segments??out?.polygons;if(Array.isArray(ms)&&ms.length)return ms.slice(0,10).map((m:any,i:number)=>{const p=m.polygon??m.points??m.contour??ds[i]?.polygon;if(!Array.isArray(p)||p.length<3)return null;return{id:String(m.id??`mask-${i+1}`),label:String(m.label??ds[i]?.label??"architectural opening"),confidence:Number(m.confidence??ds[i]?.confidence??.72),polygon:p,svgPath:m.svgPath??path(p),alphaMaskUrl:m.url??m.mask??m.mask_url}}).filter(Boolean) as Mask[];return ds.slice(0,10).map((d,i)=>({id:`det-${i+1}`,label:d.label,confidence:d.confidence,polygon:d.polygon,svgPath:path(d.polygon)}))}
