export type EP={x:number;y:number;strength?:number};
export type P={x:number;y:number};
export type B={x:number;y:number;width:number;height:number};
export type CM={id:string;type:"auto-generated";shape:"polygon";points:P[];boundingBox:B;enabled:boolean};
type C={x:number;y:number};type Cand={box:B;points:P[];score:number};
const K=(x:number,y:number)=>x+","+y;
const I=(p:EP,z:B)=>p.x>=z.x&&p.x<=z.x+z.width&&p.y>=z.y&&p.y<=z.y+z.height;
const M=(g:Uint8Array,w:number,h:number,x:number,y:number)=>{if(x>=0&&y>=0&&x<w&&y<h)g[y*w+x]=1};
const O=(a:B,b:B)=>Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y));
const X=(o:P,a:P,b:P)=>(a.x-o.x)*(b.y-o.y)-(a.y-o.y)*(b.x-o.x);
function H(ps:P[]){const s=[...ps].sort((a,b)=>a.x===b.x?a.y-b.y:a.x-b.x).filter((p,i,a)=>i===0||p.x!==a[i-1].x||p.y!==a[i-1].y);if(s.length<=3)return s;const l:P[]=[];for(const p of s){while(l.length>=2&&X(l[l.length-2],l[l.length-1],p)<=0)l.pop();l.push(p)}const u:P[]=[];for(let i=s.length-1;i>=0;i--){const p=s[i];while(u.length>=2&&X(u[u.length-2],u[u.length-1],p)<=0)u.pop();u.push(p)}u.pop();l.pop();return l.concat(u)}
function T(ps:P[],m=18){if(ps.length<=m)return ps;const r:P[]=[];const st=ps.length/m;for(let i=0;i<m;i++)r.push(ps[Math.floor(i*st)]);return r}
function L(ps:P[],b:B){return ps.map(p=>({x:+(((p.x-b.x)/Math.max(b.width,.01))*100).toFixed(2),y:+(((p.y-b.y)/Math.max(b.height,.01))*100).toFixed(2)}))}
function Cn(cells:C[],z:B,w:number,h:number):Cand|null{if(cells.length<18)return null;const xs=cells.map(c=>c.x),ys=cells.map(c=>c.y);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const cw=maxX-minX+1,ch=maxY-minY+1;const b={x:z.x+minX/w*z.width,y:z.y+minY/h*z.height,width:cw/w*z.width,height:ch/h*z.height};const area=b.width*b.height,za=z.width*z.height,asp=b.width/Math.max(b.height,.01),mx=Math.max(.8,z.width*.018),my=Math.max(.8,z.height*.018);if(b.width<z.width*.045||b.height<z.height*.055||area<za*.003||area>za*.3||asp<.22||asp>4.8)return null;if(b.x<=z.x+mx||b.y<=z.y+my||b.x+b.width>=z.x+z.width-mx||b.y+b.height>=z.y+z.height-my)return null;const set=new Set(cells.map(c=>K(c.x,c.y)));const edge=cells.filter(c=>{for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)if((x||y)&&!set.has(K(c.x+x,c.y+y)))return true;return false});const abs=edge.map(c=>({x:z.x+(c.x+.5)/w*z.width,y:z.y+(c.y+.5)/h*z.height}));const poly=T(H(abs),20);if(poly.length<3)return null;return{box:b,points:L(poly,b),score:cells.length/Math.max(cw*ch,1)*4+Math.min(2,Math.sqrt(area/Math.max(za,1))*8)+Math.min(1,poly.length/16)}}
export function generateContourMasks(edgePoints:EP[],zone:B):CM[]{const pts=edgePoints.filter(p=>I(p,zone));if(pts.length<12)return[];const W=180,Hh=180,g=new Uint8Array(W*Hh);for(const p of pts){const gx=Math.round((p.x-zone.x)/Math.max(zone.width,.01)*(W-1)),gy=Math.round((p.y-zone.y)/Math.max(zone.height,.01)*(Hh-1));for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)M(g,W,Hh,gx+x,gy+y)}const d=new Uint8Array(g.length);for(let y=0;y<Hh;y++)for(let x=0;x<W;x++)if(g[y*W+x])for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)M(d,W,Hh,x+xx,y+yy);const v=new Uint8Array(d.length),dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]],cand:Cand[]=[];for(let y=0;y<Hh;y++)for(let x=0;x<W;x++){const id=y*W+x;if(!d[id]||v[id])continue;const q:C[]=[{x,y}],cells:C[]=[];v[id]=1;while(q.length){const c=q.shift()!;cells.push(c);for(const [dx,dy] of dirs){const nx=c.x+dx,ny=c.y+dy;if(nx<0||ny<0||nx>=W||ny>=Hh)continue;const ni=ny*W+nx;if(!d[ni]||v[ni])continue;v[ni]=1;q.push({x:nx,y:ny})}}const cc=Cn(cells,zone,W,Hh);if(cc)cand.push(cc)}const acc:Cand[]=[];for(const c of cand.sort((a,b)=>b.score-a.score)){const a=c.box.width*c.box.height;let dup=false;for(const e of acc){const ea=e.box.width*e.box.height;if(O(e.box,c.box)/Math.max(1,Math.min(ea,a))>.36){dup=true;break}}if(!dup)acc.push(c);if(acc.length>=10)break}return acc.map((c,i)=>({id:`contour_mask_${Date.now()}_${i}`,type:"auto-generated",shape:"polygon",points:c.points,boundingBox:{x:+c.box.x.toFixed(2),y:+c.box.y.toFixed(2),width:+c.box.width.toFixed(2),height:+c.box.height.toFixed(2)},enabled:true}))}
