export type Point={x:number;y:number};
export type Quad=[Point,Point,Point,Point];
export type Matrix3=[number,number,number,number,number,number,number,number,number];
export const FLAT_W=1600,FLAT_H=900;
function solve(a:number[][],b:number[]){const n=b.length,m=a.map((r,i)=>[...r,b[i]]);for(let i=0;i<n;i++){let max=i;for(let r=i+1;r<n;r++)if(Math.abs(m[r][i])>Math.abs(m[max][i]))max=r;[m[i],m[max]]=[m[max],m[i]];const piv=m[i][i]||1e-12;for(let c=i;c<=n;c++)m[i][c]/=piv;for(let r=0;r<n;r++){if(r===i)continue;const f=m[r][i];for(let c=i;c<=n;c++)m[r][c]-=f*m[i][c]}}return m.map(r=>r[n])}
export function homography(src:Quad,dst:Quad):Matrix3{const a:number[][]=[],b:number[]=[];for(let i=0;i<4;i++){const{x,y}=src[i],X=dst[i].x,Y=dst[i].y;a.push([x,y,1,0,0,0,-X*x,-X*y]);b.push(X);a.push([0,0,0,x,y,1,-Y*x,-Y*y]);b.push(Y)}const h=solve(a,b);return[h[0],h[1],h[2],h[3],h[4],h[5],h[6],h[7],1]}
export function apply(m:Matrix3,p:Point):Point{const d=m[6]*p.x+m[7]*p.y+m[8];return{x:(m[0]*p.x+m[1]*p.y+m[2])/d,y:(m[3]*p.x+m[4]*p.y+m[5])/d}}
export function flatDestination(w=FLAT_W,h=FLAT_H):Quad{return[{x:0,y:0},{x:w,y:0},{x:w,y:h},{x:0,y:h}]}
export function percentToPixels(p:Point,size:{width:number;height:number}):Point{return{x:p.x/100*size.width,y:p.y/100*size.height}}
export function pixelsToPercent(p:Point,size:{width:number;height:number}):Point{return{x:p.x/size.width*100,y:p.y/size.height*100}}
export function quadPercentToPixels(q:Quad,size:{width:number;height:number}):Quad{return q.map(p=>percentToPixels(p,size)) as Quad}
export function warpImageToCanvas(image:HTMLImageElement,srcPercent:Quad,outW=FLAT_W,outH=FLAT_H){const src=quadPercentToPixels(srcPercent,{width:image.naturalWidth,height:image.naturalHeight});const inv=homography(flatDestination(outW,outH),src);const canvas=document.createElement("canvas");canvas.width=outW;canvas.height=outH;const ctx=canvas.getContext("2d");if(!ctx)return canvas;const input=document.createElement("canvas");input.width=image.naturalWidth;input.height=image.naturalHeight;const ictx=input.getContext("2d");if(!ictx)return canvas;ictx.drawImage(image,0,0);const out=ctx.createImageData(outW,outH),data=ictx.getImageData(0,0,input.width,input.height).data;for(let y=0;y<outH;y++){for(let x=0;x<outW;x++){const p=apply(inv,{x,y});const sx=Math.round(p.x),sy=Math.round(p.y),di=(y*outW+x)*4;if(sx>=0&&sy>=0&&sx<input.width&&sy<input.height){const si=(sy*input.width+sx)*4;out.data[di]=data[si];out.data[di+1]=data[si+1];out.data[di+2]=data[si+2];out.data[di+3]=255}}}ctx.putImageData(out,0,0);return canvas}
